source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-mongomapper'
gem 'oii_twitter_goodies', '0.0.81'
gem 'bson_ext'
gem 'tux'
gem 'hashie', '1.2'
gem "pry"
gem "twitter"
gem "twitter_oauth"
gem "sinatra-twitter-oauth"
gem "sinatra-flash"
gem "oauth"
gem "json"
gem "tweetstream"
gem "typhoeus"
gem "rake"
